[package]
name = "hyperloglogplus"
version = "0.1.0"
authors = ["Tasos Bakogiannis <t.bakogiannis@gmail.com>"]
description = "HyperLogLog implementations."
homepage = "https://github.com/tabac/hyperloglog.rs"
repository = "https://github.com/tabac/hyperloglog.rs"
documentation = "https://github.com/tabac/hyperloglog.rs"
readme = "README.md"
license = "MIT"
keywords = ["hyperloglog", "probabilistic", "sketch"]
edition = "2018"

[features]
# Specify this feature flag to run also unit benchmarks
# using the nightly compiler.
bench-units = []

[profile.release]
debug = true

[dev-dependencies]
rand = "0.7"
criterion = "0.3"

[[bench]]
name = "hyperloglog"
harness = false

[dependencies]
