[package]
name = "evl"
version = "0.1.0"
authors = ["Tasos Bakogiannis <t.bakogiannis@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
clap = "3.0.0-beta.1"
rayon = "1.1"
hyperloglogplus = { path = "..", features = ["const-loop"] }
